--CREATE TABLE [dbo].[StudentSessionResults] (
--    [ID]                INT     IDENTITY(1,1) PRIMARY KEY,
--    [StudentsID]         INT                     NOT NULL,
--    [ExamScheduleID]    INT                     NOT NULL,
--    [ExamValue]         INT,
--    [SetOffValue]       NVARCHAR (40)
--)