--ALTER TABLE [dbo].[ExamSchedule]
--    ADD CONSTRAINT [FK_ExamSchedule_Groups_ID] 
--	FOREIGN KEY ([GroupsID]) REFERENCES [dbo].[Groups] ([ID]) 
--	ON DELETE NO ACTION ON UPDATE NO ACTION;
--GO
--
--ALTER TABLE [dbo].[ExamSchedule]
--    ADD CONSTRAINT [FK_ExamSchedule_NumberOfSession_ID] 
--	FOREIGN KEY ([NumberOfSessionID]) REFERENCES [dbo].[NumberOfSession] ([ID]) 
--	ON DELETE NO ACTION ON UPDATE NO ACTION;
--GO