// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Стиль", "IDE0059:Ненужное присваивание значения", Justification = "<Ожидание>", Scope = "member", Target = "~M:InheritanceInterfacesAbstractAndClasses.Tests.RectangleTests.GivenASide_ForRectangleWhen_aSide_minus2ThenOutIsArgumentException")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Стиль", "IDE0059:Ненужное присваивание значения", Justification = "<Ожидание>", Scope = "member", Target = "~M:InheritanceInterfacesAbstractAndClasses.Tests.RectangleTests.GivenBSide_ForRectangleWhen_bSide_minus2ThenOutIsArgumentException")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Стиль", "IDE0059:Ненужное присваивание значения", Justification = "<Ожидание>", Scope = "member", Target = "~M:InheritanceInterfacesAbstractAndClasses.Tests.RectangleTests.GivenASide_ForRectangleWhen_aSide_ZeroThenOutIsArgumentException")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Стиль", "IDE0059:Ненужное присваивание значения", Justification = "<Ожидание>", Scope = "member", Target = "~M:InheritanceInterfacesAbstractAndClasses.Tests.RectangleTests.GivenGetAreaFigure_ForRectangleWhen_aSideAndbSide_minus2ThenOutIsArgumentException")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Стиль", "IDE0059:Ненужное присваивание значения", Justification = "<Ожидание>", Scope = "member", Target = "~M:InheritanceInterfacesAbstractAndClasses.Tests.RectangleTests.GivenBSide_ForRectangleWhen_bSide_ZeroThenOutIsArgumentException")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Стиль", "IDE0059:Ненужное присваивание значения", Justification = "<Ожидание>", Scope = "member", Target = "~M:InheritanceInterfacesAbstractAndClasses.Tests.RectangleTests.GivenGetAreaFigure_ForRectangleWhen_sidesIsZeroThenOutIsArgumentException")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Стиль", "IDE0059:Ненужное присваивание значения", Justification = "<Ожидание>", Scope = "member", Target = "~M:InheritanceInterfacesAbstractAndClasses.Tests.RectangleTests.GivenGetPerimeterFigure_ForRectangleWhen_sidesIsMinus2ThenOutIsArgumentException")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Стиль", "IDE0059:Ненужное присваивание значения", Justification = "<Ожидание>", Scope = "member", Target = "~M:InheritanceInterfacesAbstractAndClasses.Tests.RectangleTests.GivenGetPerimeterFigure_ForRectangleWhen_sidesIsZeroThenOutIsArgumentException")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Стиль", "IDE0059:Ненужное присваивание значения", Justification = "<Ожидание>", Scope = "member", Target = "~M:InheritanceInterfacesAbstractAndClasses.Tests.SquareTests.GivenASide_ForSquereWhen_aSide_ZeroThenOutIsArgumentException")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Стиль", "IDE0059:Ненужное присваивание значения", Justification = "<Ожидание>", Scope = "member", Target = "~M:InheritanceInterfacesAbstractAndClasses.Tests.SquareTests.GivenGetAreaFigure_ForSquereWhen_aSide_minus2ThenOutIsArgumentException")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Стиль", "IDE0059:Ненужное присваивание значения", Justification = "<Ожидание>", Scope = "member", Target = "~M:InheritanceInterfacesAbstractAndClasses.Tests.SquareTests.GivenASide_ForSquereWhen_aSide_minus2ThenOutIsArgumentException")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Стиль", "IDE0059:Ненужное присваивание значения", Justification = "<Ожидание>", Scope = "member", Target = "~M:InheritanceInterfacesAbstractAndClasses.Tests.SquareTests.GivenGetAreaFigure_ForSquereWhen_aSide_ZeroThenOutIsArgumentException")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Стиль", "IDE0059:Ненужное присваивание значения", Justification = "<Ожидание>", Scope = "member", Target = "~M:InheritanceInterfacesAbstractAndClasses.Tests.SquareTests.GivenGetPerimeterFigure_ForSquereWhen_aSide_minus2ThenOutIsArgumentException")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Стиль", "IDE0059:Ненужное присваивание значения", Justification = "<Ожидание>", Scope = "member", Target = "~M:InheritanceInterfacesAbstractAndClasses.Tests.SquareTests.GivenGetPerimeterFigure_ForSquereWhen_aSide_ZeroThenOutIsArgumentException")]
