// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Стиль", "IDE0059:Ненужное присваивание значения", Justification = "<Ожидание>", Scope = "member", Target = "~M:DeclaringAndCallingMethodsTests.AlgorithmGcdTests.GivenGetEuclidGcd_ForTwoNumWhenNumbersIsPositiveOutIsPositive")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Стиль", "IDE0059:Ненужное присваивание значения", Justification = "<Ожидание>", Scope = "member", Target = "~M:DeclaringAndCallingMethodsTests.AlgorithmGcdTests.GivenGetEuclidGcd_ForTwoNumWhenNumbersIsNegativeOutIsPositive")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Стиль", "IDE0059:Ненужное присваивание значения", Justification = "<Ожидание>", Scope = "member", Target = "~M:DeclaringAndCallingMethodsTests.AlgorithmGcdTests.GivenGetEuclidGcd_ForTwoNumWhenNumbersIsNegativeAndPositiveOutIsPositive")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Стиль", "IDE0059:Ненужное присваивание значения", Justification = "<Ожидание>", Scope = "member", Target = "~M:DeclaringAndCallingMethodsTests.AlgorithmGcdTests.GivenGetEuclidGcd_ForFourNumWhenNumbersIsNegativeAndPositiveOutIsPositive")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Стиль", "IDE0059:Ненужное присваивание значения", Justification = "<Ожидание>", Scope = "member", Target = "~M:DeclaringAndCallingMethodsTests.AlgorithmGcdTests.GivenGetEuclidGcd_ForFourNumWhenNumbersIsNegativeOutIsPositive")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Стиль", "IDE0059:Ненужное присваивание значения", Justification = "<Ожидание>", Scope = "member", Target = "~M:DeclaringAndCallingMethodsTests.AlgorithmGcdTests.GivenGetEuclidGcd_ForFourNumWhenNumbersIsPositiveOutIsPositive")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Стиль", "IDE0059:Ненужное присваивание значения", Justification = "<Ожидание>", Scope = "member", Target = "~M:DeclaringAndCallingMethodsTests.AlgorithmGcdTests.GivenGetEuclidGcd_ForFourNumWhenOneOfNumbersIsZeroOutIsPositive")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Стиль", "IDE0059:Ненужное присваивание значения", Justification = "<Ожидание>", Scope = "member", Target = "~M:DeclaringAndCallingMethodsTests.AlgorithmGcdTests.GivenGetEuclidGcd_ForThreeNumWhenNumbersIsNegativeAndPositiveOutIsPositive")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Стиль", "IDE0059:Ненужное присваивание значения", Justification = "<Ожидание>", Scope = "member", Target = "~M:DeclaringAndCallingMethodsTests.AlgorithmGcdTests.GivenGetEuclidGcd_ForThreeNumWhenNumbersIsNegativeOutIsPositive")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Стиль", "IDE0059:Ненужное присваивание значения", Justification = "<Ожидание>", Scope = "member", Target = "~M:DeclaringAndCallingMethodsTests.AlgorithmGcdTests.GivenGetEuclidGcd_ForThreeNumWhenNumbersIsPositiveOutIsPositive")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Стиль", "IDE0059:Ненужное присваивание значения", Justification = "<Ожидание>", Scope = "member", Target = "~M:DeclaringAndCallingMethodsTests.AlgorithmGcdTests.GivenGetEuclidGcd_ForThreeNumWhenOneOfNumbersIsZeroOutIsPositive")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Стиль", "IDE0059:Ненужное присваивание значения", Justification = "<Ожидание>", Scope = "member", Target = "~M:DeclaringAndCallingMethodsTests.AlgorithmGcdTests.GivenGetEuclidGcd_ForTwoNumWhenOneOfNumbersIsZeroOutIsPositive")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Стиль", "IDE0059:Ненужное присваивание значения", Justification = "<Ожидание>", Scope = "member", Target = "~M:DeclaringAndCallingMethodsTests.AlgorithmGcdTests.GivenGetBinaryGcd_ForFourNumWhenNumbersIsNegativeAndPositiveOutIsPositive")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Стиль", "IDE0059:Ненужное присваивание значения", Justification = "<Ожидание>", Scope = "member", Target = "~M:DeclaringAndCallingMethodsTests.AlgorithmGcdTests.GivenGetBinaryGcd_ForFourNumWhenNumbersIsNegativeOutIsPositive")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Стиль", "IDE0059:Ненужное присваивание значения", Justification = "<Ожидание>", Scope = "member", Target = "~M:DeclaringAndCallingMethodsTests.AlgorithmGcdTests.GivenGetBinaryGcd_ForFourNumWhenNumbersIsPositiveOutIsPositive")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Стиль", "IDE0059:Ненужное присваивание значения", Justification = "<Ожидание>", Scope = "member", Target = "~M:DeclaringAndCallingMethodsTests.AlgorithmGcdTests.GivenGetBinaryGcd_ForFourNumWhenOneOfNumbersIsZeroOutIsPositive")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Стиль", "IDE0059:Ненужное присваивание значения", Justification = "<Ожидание>", Scope = "member", Target = "~M:DeclaringAndCallingMethodsTests.AlgorithmGcdTests.GivenGetBinaryGcd_ForThreeNumWhenNumbersIsNegativeAndPositiveOutIsPositive")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Стиль", "IDE0059:Ненужное присваивание значения", Justification = "<Ожидание>", Scope = "member", Target = "~M:DeclaringAndCallingMethodsTests.AlgorithmGcdTests.GivenGetBinaryGcd_ForThreeNumWhenNumbersIsNegativeOutIsPositive")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Стиль", "IDE0059:Ненужное присваивание значения", Justification = "<Ожидание>", Scope = "member", Target = "~M:DeclaringAndCallingMethodsTests.AlgorithmGcdTests.GivenGetBinaryGcd_ForThreeNumWhenNumbersIsPositiveOutIsPositive")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Стиль", "IDE0059:Ненужное присваивание значения", Justification = "<Ожидание>", Scope = "member", Target = "~M:DeclaringAndCallingMethodsTests.AlgorithmGcdTests.GivenGetBinaryGcd_ForThreeNumWhenOneOfNumbersIsZeroOutIsPositive")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Стиль", "IDE0059:Ненужное присваивание значения", Justification = "<Ожидание>", Scope = "member", Target = "~M:DeclaringAndCallingMethodsTests.AlgorithmGcdTests.GivenGetBinaryGcd_ForTwoNumWhenNumbersIsNegativeAndPositiveOutIsPositive")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Стиль", "IDE0059:Ненужное присваивание значения", Justification = "<Ожидание>", Scope = "member", Target = "~M:DeclaringAndCallingMethodsTests.AlgorithmGcdTests.GivenGetBinaryGcd_ForTwoNumWhenNumbersIsNegativeOutIsPositive")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Стиль", "IDE0059:Ненужное присваивание значения", Justification = "<Ожидание>", Scope = "member", Target = "~M:DeclaringAndCallingMethodsTests.AlgorithmGcdTests.GivenGetBinaryGcd_ForTwoNumWhenNumbersIsPositiveOutIsPositive")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Стиль", "IDE0059:Ненужное присваивание значения", Justification = "<Ожидание>", Scope = "member", Target = "~M:DeclaringAndCallingMethodsTests.AlgorithmGcdTests.GivenGetBinaryGcd_ForTwoNumWhenOneOfNumbersIsZeroOutIsPositive")]
